
- name: set hostname if necessary
  hostname:
    name: "{{ inventory_hostname | regex_replace('\\.', '-') }}"

- name: load packages list
  include_vars:
    file: "../vars/pkg-{{ ansible_distribution }}.yml"

- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages|flatten(levels=1) }}"

- include: set_vars.yml

- include: disable-iptables.yml
