- name: remove current if update
  shell: docker rm -f eru-core
  ignore_errors: yes
  when: upgrade

- name: inspect core container
  shell: docker inspect eru-core
  register: inspect_core
  ignore_errors: yes

- name: run core container
  shell: docker run -d --name eru-core --net host --restart always -v /etc/eru:/etc/eru projecteru2/core /usr/bin/eru-core
  when: inspect_core.rc != 0
