- name: remove current if update
  shell: docker rm -f eru-core
  ignore_errors: yes
  when: upgrade

- name: run core container
  shell: docker run -d --name eru-core --net host --restart always -v /etc/eru:/etc/eru projecteru2/core /usr/bin/eru-core
  register: res
  failed_when: res.rc != 0 and 'Conflict' not in res.stderr
