- name: add golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present

- name: install golang
  apt:
    name: golang-go
    state: latest
    update_cache: yes

- name: install cli
  shell: GO111MODULE=on go get github.com/projecteru2/cli

- name: add cli into $PATH
  lineinfile:
    path: /root/.bashrc
    line: PATH=/root/go/bin:$PATH
