- name: ensure etcd config dir
  file:
    path: /etc/etcd/
    state: directory

- name: ensure etcd data dir
  file:
    path: /var/lib/etcd/
    state: directory

- name: template etcd config
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf

- name: template systemd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
