- name: render calico resource yaml
  template:
    src: "{{ item }}.yml.j2"
    dest: /tmp/{{ item }}.yml
  loop:
    - ippool
    - profile

- name: create calico ippool
  shell: calicoctl create -f /tmp/ippool.yml
  register: res
  failed_when: res.rc != 0 and 'resource already exists' not in res.stdout

- name: create calico profile
  shell: calicoctl create -f /tmp/profile.yml
  register: res
  failed_when: res.rc != 0 and 'resource already exists' not in res.stdout
