- name: docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: docker service
  template:
    src: docker.service.j2
    dest: /lib/systemd/system/docker.service
